### ISSUE TITLE
Sitting animation doesn't work in 3rd person view

### ISSUE THREAD

**Issue by MarkuBu** [Thomas--S/ts_furniture#3]
If you sit on a chair while in 3rd person view the sitting animation doesn't work. The player stands on the chair

**Comment by Thomas--S** [comment]
Thanks for the bug report.
At the moment I'm quite busy, but I'll look at this as soon as I have time for it.

**Comment by Thomas--S** [comment]
I looked at this issue again and I fear it's a engine-side problem. I have no idea how to fix this. If someone else knows better, feel free to help!

**Comment by Poikilos** [comment]
@MarkuBu Is this fixed? This seems to work as of the ts_furniture version I was using Feb 2018 for fixing the sitting height, with 5.0.0-dev at least.

**Comment by Thomas--S** [comment]
It seems like there are still problems when you sit down while in 3rd person mode.

**Comment by Poikilos** [comment]
For me, the y position was working with my patch in Aug 2018, but now with recent version of minetest 5.0.0-dev the player sits on the ground inside chair (legs are bent though). This behavior is the same with or without playeranim installed (legs are bent either way, but player is too low either way). Maybe I was using a version of minetest 5.0.0-dev from before Nov 2017 when tested in Aug 2018--according to @Rui-Minetest from minetest_mods/playeranim, the model changed Nov 2017. I would like to help but need more information. Do you know the answers to the following questions, or know who does?
* when was the model version bumped in minetest (I assume minetest_game doesn't have anything to do with positioning the model and that minetest controls this)
* is the model "v3" used for every minetest 5.0.0-dev (and for "0.5.0-dev" as it was called earlier) always the same, or was it changed sometime afterward (playeranim has so far decided that there is "[no automatic way](https://github.com/minetest-mods/playeranim/blob/master/README.md)" to [detect](https://github.com/minetest-mods/playeranim/issues/19) model version--see below)
* is there a known time when this broke (when engine changed--did player offset change more than once during development of minetest)
* are legs straight only using 0.4.*
* if the bug is only with 0.4.*, is it only _without_ playeranim (I am able to get legs to bend in 5.0.0-dev even without playeranim)
* if you use playeranim, have you checked minetest.conf? It now requires a **different** line than it did before:
```
# 5.0.0-dev:
# setting formerly used by playeranim:
# player_model_version = default_character_v3
# setting currently used by playeranim:
playeranim.model_version = MTG_4_Nov_2017

# 0.4.*:
# setting formerly used by playeranim:
# player_model_version = default_character_v2
# setting currently used by playeranim:
playeranim.model_version = MTG_4_Jun_2017

```

For testing 5.0.0-dev, try updating if you are using git version master branch, and also updating minetest_game--if on linux, try my script:
```
wget -O install-minetestserver-git-all-backends.sh https://github.com/poikilos/EnlivenMinetest/raw/master/install-minetestserver-git-all-backends.sh
chmod +x install-minetestserver-git-all-backends.sh
./install-minetestserver-git-all-backends.sh both
#params:
# * both: installs minetestserver & minetest
# * client: installs minetest (client only)
# * (no param): installs server
```

**Comment by Thomas--S** [comment]
Actually, I don't know the answers to your questions.
I don't use playeranim, and I used the latest 5.0.0-dev git version for testing.
I will try to find a working solution as soon as 5.0.0 is ready for release, so we have a stable mod again.

Thanks for your contributions to this mod!

**Comment by MoNTE48** [comment]
After 2.5 years, let me take a look at the problem...
Ah, here is the fix. Enjoy :)
https://github.com/minetest-mods/ts_furniture/pull/11/commits/01c9511e307a22bd54d37799e246581ea00cc592
(not related to the model or anything else mentioned above)
